image:
  - Visual Studio 2019

install: 
  - curl -o C:\SDL2.zip https://www.libsdl.org/release/SDL2-devel-2.0.12-VC.zip
  - curl -o C:\SDL2_net.zip https://www.libsdl.org/projects/SDL_net/release/SDL2_net-devel-2.0.1-VC.zip
  - 7z x C:\SDL2.zip -oC:\ -y
  - move C:\SDL2-2.0.12 C:\SDL2
  - 7z x C:\SDL2_net.zip -oC:\ -y  
  - move C:\SDL2_net-2.0.1 C:\SDL2_net
  - dir /s C:\SDL2

platform: x64

build:
  project: OpenDIS.sln

before_build:
  - cmake -DSDL2_PATH=C:\SDL2\lib\x64 -DSDL2_INCLUDE_DIR=C:\SDL2\include -DSDL2_NET_PATH=C:\SDL2_net\lib\x64 -DSDL2_NET_INCLUDE_DIR=C:\SDL2_net\include .
  - dir
